### ISSUE TITLE
Problem with download langauge pack

### ISSUE THREAD

**Issue by royalfoxie** [fsondej/autocorrect#40]
Hi, I have some problems with download polish package. Looks like dropbox block the link.

`couldn't download https://dl.dropboxusercontent.com/s/40orabi1l3dfqpp/pl.tar.gz?dl=0, trying next url...
Traceback (most recent call last):
  File "C:\Users\lisek\Desktop\test.py", line 15, in <module>
    spell = Speller('pl')
  File "D:\Python\lib\site-packages\autocorrect\__init__.py", line 78, in __init__
    self.nlp_data = load_from_tar(lang) if nlp_data is None else nlp_data
  File "D:\Python\lib\site-packages\autocorrect\__init__.py", line 61, in load_from_tar
    raise ConnectionError(
ConnectionError: HTTP Error 429: Too Many Requests
Fix your network connection, or manually download`

Is there any chance to get language pack another way?

**Comment by filyp** [comment]
Yeah, it looks that we overloaded dropbox. I just moved all the dictionaries to IPFS. 
In the new version (2.5.1) this should work fine.

**Comment by filyp** [comment]
Yeah, it looks that we overloaded dropbox. I just moved all the dictionaries to IPFS.
In the new version (2.5.1) this should work fine.

**Comment by filyp** [comment]
Let me know if it fixed your problem.

**Comment by symbwell** [comment]
Hi, your fix solve the problem. Thanks :)
