### ISSUE TITLE
Is it possible to get the most close words to the typed instance? Currently, Speller() only return a single word. 

### ISSUE THREAD

**Issue by alikaz3mi** [fsondej/autocorrect#41]

**Comment by filyp** [comment]
Yeah, you can use Speller's method `get_candidates`.
https://github.com/filyp/autocorrect/blob/fa317475115f0f07f93e8f598395b6fca2d8271f/autocorrect/__init__.py#L96

**Comment by David-Baron** [comment]
@filyp  Can be added to readme?

**Comment by filyp** [comment]
Added to readme
