### ISSUE TITLE
French Spell Checker

### ISSUE THREAD

**Issue by oscar-defelice** [fsondej/autocorrect#43]
I followed your instructions but I got an error when I try to count words from language corpus.
I attach a screenshot here, but the error log is the following

```bash
~/miniconda3/envs/cs/lib/python3.8/site-packages/autocorrect/word_count.py in get_words(filename, lang, encd)
      7 
      8 def get_words(filename, lang, encd):
----> 9     word_regex = word_regexes[lang]
     10     capitalized_regex = r'(\.|^|<|"|\'|\(|\[|\{)\s*' + word_regexes[lang]
     11     with open(filename, encoding=encd) as file:

KeyError: 'fr'
```

My guess is that this is related to the key languages present in `word_regexes` dict.

![image](https://user-images.githubusercontent.com/49638680/142235505-fcf78a3a-68ac-45ff-8441-9ef4c8f53628.png)

**Comment by oscar-defelice** [comment]
After a bit of browsing in the code, I guess (but please correct me if I am wrong) what should be done in order to add a new language is
1. first add the corresponding keys in `autocorrect.constants` dictionaries
2. follow the readme instructions

**Comment by filyp** [comment]
You're right, I forgot to mention it in readme. Thanks for catching that!
You need to add an entry both in `word_regexes` and `alphabets` dicts.
