### ISSUE TITLE
Spell Check Multiple Languages Simultaneously in a Multi-lingual Setup

### ISSUE THREAD

**Issue by blahiri** [fsondej/autocorrect#46]
Hi, I was wondering if autocorrect can utilize multiple languages simultaneously in a multi-lingual setup.

For example,

<pre>
from autocorrect import Speller

spellcheck = Speller(lang='en', 'es', 'fr')

corrected_text = spellcheck(text)
</pre>

**Comment by filyp** [comment]
This is not supported, but you could get something close by instantiating several spellers, each with a different language, and passing some sentence through all of them in sequence.
