### ISSUE TITLE
How to use Speller(lang='vi')

### ISSUE THREAD

**Issue by nam157** [fsondej/autocorrect#47]
![image](https://user-images.githubusercontent.com/72034584/172177447-ab97adfe-4c62-4108-9c67-b1cdd5b713de.png)

**Comment by nam157** [comment]
how to download vietnamese dictionary ???

**Comment by filyp** [comment]
It says "done", so it looks like finally it was downloaded correctly. What happens when you try to use it?

**Comment by nam157** [comment]
I try it, but it's not correct, how to improve it

**Comment by nam157** [comment]
is it possible to change another vietnamese dictionary

**Comment by filyp** [comment]
So there's no error, but just bad autocorrect ion quality?
You can create your own dictionary by following instructions in the readme:
https://github.com/filyp/autocorrect#adding-new-languages
