### ISSUE TITLE
Italian languange not working

### ISSUE THREAD

**Issue by SebastianS93** [fsondej/autocorrect#48]
Hi, i'm trying to load and run spell check with italian language (supported) with current script

`from autocorrect import Speller`
`spell = Speller(lang='it')`
`result = spell('Ciaa da uma perzona itaviana')`
`print(result);`

....but i receive the following error

![image](https://user-images.githubusercontent.com/60503318/173052503-dcabcd51-71e2-4c92-9d76-3d777bf046a6.png)

Can you help us? We're building a big project upon this library.

Wish you my best regards,
Sebastian

**Comment by filyp** [comment]
Hm, it looks like Italian dictionary got downloaded incorrectly, maybe due to some network error. Try deleting it (or reinstalling the library) and try again.

**Comment by SebastianS93** [comment]
If I uninstall the package and reinstall it, it gives me the same error, I'll proceed with manual italian installation.

**Comment by filyp** [comment]
Also, just checked again, and IPFS worked and the Italian dict stored there is fine. It must have got corrupted when you downloaded it partially, and later pip doesn't remove the file when uninstalling.

You could try to locate the file and delete it manually, or install autocorrect from scratch in some venv.
