### ISSUE TITLE
Reference Norvig's spelling corrector in readme

### ISSUE THREAD

**Issue by Dobatymo** [fsondej/autocorrect#52]
Hi, since the code or at least the algorithm is based on Peter Norvig's spelling corrector https://norvig.com/spell-correct.html you should mention it in the readme file. This way the advanced reader will quickly get an idea of the implementation.
Right now it's only mentioned here https://github.com/filyp/autocorrect/blob/0fa2a7cab20a44b9d8393246d9553629bb35e077/autocorrect/typos.py

**Comment by filyp** [comment]
Done.
https://github.com/filyp/autocorrect/commit/cc9c5d87a01c53581f985896096c47697763ed0c
